language: php

php:
  # PHP 5.5 is failing because mysql extension is deprecated
  #- 5.5
  - 5.4
  - 5.3.3
  - 5.3
  # hhvm is failing because the dataset insertion does not work for unknown reason
  #- hhvm

before_script:
  - composer self-update
  - composer install
  - mysql -u root -e "DROP DATABASE IF EXISTS dsplib_test;"
  - mysql -u root -e "CREATE DATABASE dsplib_test;"
  - mysql -u root -e "CREATE USER 'dsplib'@'localhost' IDENTIFIED BY 'dsplib';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON dsplib_test.* TO 'dsplib'@'localhost';"

