language: php

php:
  - 5.5
  - 5.4
  - 5.3.3
  - 5.3
  - hhvm

before_script:
  - composer self-update
  - composer install
  - echo "USE mysql;\nCREATE USER dsplib IDENTIFIED BY 'dsplib';\nGRANT ALL PRIVILEGES ON *.* TO 'dsplib'@'localhost';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "CREATE DATABASE dsplib_test;" | mysql -u dsplib -pdsplib
  - echo "USE dsplib_test;\nCREATE TABLE table1 (idtable1 int(11) unsigned NOT NULL AUTO_INCREMENT, name varchar(32) NOT NULL DEFAULT '', value varchar(32) NOT NULL DEFAULT '', PRIMARY KEY (idtable1)) ENGINE=MyISAM DEFAULT CHARSET=latin1;\n" | mysql -u dsplib -pdsplib
  - echo "USE dsplib_test;\nCREATE TABLE table1_innodb (idtable1 int(11) unsigned NOT NULL AUTO_INCREMENT, name varchar(32) NOT NULL DEFAULT '', value varchar(32) NOT NULL DEFAULT '', PRIMARY KEY (idtable1)) ENGINE=InnoDB DEFAULT CHARSET=latin1;\n" | mysql -u dsplib -pdsplib
  - echo "USE dsplib_test;\nINSERT INTO table1 (name, value) VALUES ('a', 1), ('b', 2), ('c', 3);\n" | mysql -u dsplib -pdsplib
  - echo "USE dsplib_test;\nINSERT INTO table1_innodb (name, value) VALUES ('a', 1), ('b', 2), ('c', 3);\n" | mysql -u dsplib -pdsplib

